name: Build and Push Docker Image to Azure Container Registry

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      env:
        ACR_NAME: casecloudregistory
        IMAGE_NAME: petclinic_spring_app
        IMAGE_TAG: $(date +%s)
      run: |
        docker buildx build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG . --load
        docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG
